import { Inter } from "next/font/google";
import  "@/index.scss";
import localFont from 'next/font/local'

// const myFont = localFont({ src: './my-font.woff2' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en" suppressHydrationWarning={false}>
      <body className={'layout'}>{children}</body>
    </html>
  );
}
